### ISSUE TITLE
What hardware are you using?

### ISSUE THREAD

**Issue by robbiet480** [zeroflow/ESPAircon#1]
Out of curiosity, which specific ESP are you using? It's unclear from the code, README and wiki...

Thanks, looking forward to implementing this on my Seville Classic fan this weekend hopefully.

**Comment by zeroflow** [comment]
Sorry for the late comment - but I used a Witty Cloud Board, but any generic ESP Breakout will work. 

The full schematic is already in the wiki with the exact pins used: https://github.com/zeroflow/ESPAircon/wiki
